import {learningCard,journeyStep,discoveryNotice} from './learning.mjs?v=3';
import {prepareData,hash} from './data.mjs?v=3';
import {buildCampaign,roomUnlocked,canTravel,hasFastTravel,arriveAt,reconcileCampaign} from './campaign.mjs?v=3';
import {createRun,step,currentEncounter,availableRelations,cycleCapability,objective,useAbility} from './engine.mjs?v=3';
import {readProgress,writeProgress,captureProgress,freshProgress,reconcileProgress,restartProgress} from './storage.mjs?v=3';
import {Renderer} from './renderer.mjs?v=3';
import {createInput} from './input.mjs?v=3';
import {createAudio} from './audio.mjs?v=3';
import {powerStyle,ABILITIES} from './config.mjs?v=3';
import {esc,knowledgeHTML,mapHTML,recapHTML,finaleHTML,gateURL} from './ui.mjs?v=3';

const $=id=>document.getElementById(id),canvas=$('game'),audio=createAudio(),motionQuery=matchMedia('(prefers-reduced-motion: reduce)');
const discoveryQueue=[],noticeQueue=[];let deliveryUntil=0;
let storage,renderer,data,worlds=[],progress,run,index=0,mode='loading',dialogPrevious='ready',lastFocus=null,lastTime=0,accumulator=0,toastUntil=0,lastHUD=0,lastHUDFocus=null,lastRender=0,storageWarned=false;
try{renderer=new Renderer(canvas);}catch(error){console.error(error);}
const input=createInput(canvas,{isPlaying:()=>mode==='playing',pause:togglePause,lostFocus:()=>{if(mode==='playing')pause();},cycle:cycle,knowledge:()=>showKnowledge(),map:showMap,family:i=>applyAbility(Object.keys(ABILITIES)[i]),portals:showPortals});
function notify(message,seconds=4){$('toast').textContent=message;toastUntil=performance.now()+seconds*1000;}
function persist(){if(!progress)return;if(run)progress=captureProgress(progress,run,data);if(!writeProgress(storage,progress)&&!storageWarned){storageWarned=true;notify('This browser cannot save progress. You can keep playing.',6);}}
function reduced(){return motionQuery.matches||progress?.settings.reducedMotion===true;}
function applySettings(){if(renderer)renderer.reduced=reduced();document.body.classList.toggle('no-motion',reduced());$('sound').setAttribute('aria-pressed',String(!!progress?.settings.sound));$('sound').setAttribute('aria-label',progress?.settings.sound?'Mute music and sound':'Enable music and sound');$('sound').title=progress?.settings.sound?'Music and sound on':'Music and sound off';}
motionQuery.addEventListener('change',applySettings);

function gates(){
  $('gates').style.gridTemplateColumns=`repeat(${worlds.length},1fr)`;
  $('gates').innerHTML=worlds.map((w,i)=>{const completed=progress.completed.includes(w.gate.id),unlocked=i===0||progress.completed.includes(worlds[i-1].gate.id);return `<button class="gate ${i===index?'active':''} ${completed?'done':''}" data-level="${i}" ${unlocked?'':'disabled'} ${i===index?'aria-current="step"':''} aria-label="Stage Gate ${esc(w.gate.id)}: ${esc(w.gate.label)}${completed?', journey completed':unlocked?'':', not yet reached'}"><b>${completed?'✓':i+1}</b><span>${esc(w.alias)}</span></button>`;}).join('');
  $('gates').querySelectorAll('[data-level]').forEach(b=>b.onclick=()=>{persist();prepare(Number(b.dataset.level));});
}

function hud(){
  if(!run)return;$('journeySteps').querySelectorAll('li').forEach((li,i)=>{li.classList.toggle('active',i===journeyStep(run));li.setAttribute('aria-current',i===journeyStep(run)?'step':'false');});const e=currentEncounter(run),selected=run.selected&&data.enablerMap.get(run.selected);$('portals').disabled=false;$('portals').textContent=hasFastTravel(run)?'◎ Fast travel':'◎ Portals';
  $('chapterAlias').textContent=`STAGE GATE ${run.world.gate.id} · ${run.world.alias} · MAP ${(run.world.roomIndex||0)+1}/${run.world.roomCount||1}`;$('gateTitle').textContent=run.world.gate.label;
  $('contextKicker').textContent=e?`${e.opened?'PATH OPENED':e.encountered?'ENCOUNTERED':'EXPLORE'}${e.knot?' · CONNECTED SYSTEMS':''}`:run.world.epilogue?'A NARRATIVE HANDOVER':'EXPLORE AT YOUR OWN PACE';
  $('objective').textContent=objective(run);$('coverage').textContent=`${run.encounters.length} blockers in this mini-map · ${run.world.chapterIds.filter(id=>run.priorOpened.has(id)||run.encounters.some(e=>e.id===id&&e.opened)).length}/${run.world.chapterIds.length} paths opened in this Stage Gate`;
  $('selectedCapability').textContent=selected?.title||'No capabilities discovered yet';$('inventoryButton').title=selected?.title||'Explore to discover a capability';
  $('inventoryButton').disabled=!run.inventory.size;$('touchCycle').disabled=!run.inventory.size;
  $('knowledge').disabled=!e&&!run.world.epilogue&&!run.world.unavailable;
  $('powerTray').innerHTML=data.mechanisms.map(m=>{const found=run.mechanisms.has(m.key),active=e?e.relations.some(r=>r.enablerId===run.selected&&r.mechanism===m.key):data.relationships.some(r=>r.enablerId===run.selected&&r.mechanism===m.key);return `<button class="power ${found?'discovered':''} ${active?'active':''}" data-family="${esc(m.key)}" style="--power:${m.style.color}" aria-label="${esc(m.key)}: ${esc(ABILITIES[m.key]?.name||'Activate')} · key ${esc(ABILITIES[m.key]?.key||'')}${found?', ready':', undiscovered'}" aria-pressed="${active}"><b aria-hidden="true">${m.style.symbol}</b>${esc(ABILITIES[m.key]?.key||'')} ${esc(m.key)}</button>`;}).join('');
  $('powerTray').querySelectorAll('[data-family]').forEach(b=>b.onclick=()=>applyAbility(b.dataset.family));
}

function overlay({title,text,button,kicker='A LIVING KNOWLEDGE LANDSCAPE',note='',extra='',map=false}){
  $('overlayTitle').textContent=title;$('overlayText').textContent=text;$('overlayKicker').textContent=kicker;$('overlayNote').textContent=note;$('overlayExtra').innerHTML=extra;$('start').textContent=button;$('start').disabled=false;$('overlayMap').hidden=!map;$('overlay').hidden=false;
}
function prepare(i,room=0){
  discoveryQueue.length=0;noticeQueue.length=0;$('delivery').hidden=true;audio.setPlaying(false);index=i;run=createRun(worlds[i].rooms[room]||worlds[i].rooms[0],progress);mode='ready';input.clear();renderer.reset(run);$('toast').textContent='';$('pause').disabled=true;$('mapButton').disabled=false;$('orientation').disabled=false;$('restart').disabled=false;gates();hud();
  const learned=run.inventory.size>0,empty=run.world.epilogue||run.world.unavailable;
  overlay({title:i===0&&!learned?'A little light. A world of possibility.':run.world.alias.toLowerCase().replace(/^./,s=>s.toUpperCase())+'.',text:empty?'Carry what you have learned through the living network. Visit the handover signals, then return to the central portal.':'1. Find a blocker. 2. Collect ALL its linked gold tools. 3. Return to that blocker and press E / Use (or a linked ability key). 4. Use the CENTRAL PORTAL to enter the next mini-map. Open every blocker in this Stage Gate to finish it.',button:learned?'Continue this path →':'Begin the journey →',kicker:`STAGE GATE ${run.world.gate.id} · ${run.world.gate.label}`,note:run.world.epilogue?'No mapped blocker challenges in this gate. This epilogue uses narrative game metaphors.':run.world.unavailable?'Mapped blockers exist, but usable enabling relationships are not available. This is a narrative fallback.':`Mini-map ${run.world.roomIndex+1} / ${run.world.roomCount} · ${run.world.chapterIds.length} playable blockers across this Stage Gate. All their linked enablers are included.`,map:true});
  progress.settings.currentGate=run.world.gate.id;progress.settings.currentRoom=run.world.roomIndex;persist();
}
function play(){
  if(mode==='error'){load();return;}
  if(mode==='complete'){if(index<worlds.length-1){prepare(index+1);return;}newPath();return;}
  if(!run)return;mode='playing';input.clear();$('overlay').hidden=true;$('pause').disabled=false;$('pause').textContent='Ⅱ';$('pause').setAttribute('aria-label','Pause game');audio.unlock(progress.settings.sound);audio.setPlaying(true);lastTime=performance.now();accumulator=0;canvas.focus({preventScroll:true});
  if(innerWidth<600)$('gameShell').scrollIntoView({block:'start',behavior:'instant'});
}
function pause(){if(mode!=='playing')return;mode='paused';audio.setPlaying(false);input.clear();persist();$('pause').textContent='▶';$('pause').setAttribute('aria-label','Resume game');overlay({title:'A quiet moment.',text:'Your place in the network is saved. Take a look at the map, or continue when you are ready.',button:'Return to the spark →',kicker:run.world.gate.label,note:'No timer. No score. Discover the system at your own pace.',map:true});}
function togglePause(){if(mode==='paused')play();else pause();}
function newPath(seed=String(crypto.getRandomValues(new Uint32Array(1))[0])){progress=restartProgress(progress,data,seed);worlds=buildCampaign(data,progress.seed);run=null;lastHUDFocus=null;accumulator=0;prepare(0);}
function requestRestart(){
  if(!run)return;
  showPanel('START AGAIN',`<h2>Restart the journey?</h2><p>Return to Stage Gate 1 with the same challenges. This clears completed chapters, discovered capabilities and opened paths from this game on this device.</p><p>Your sound and motion preferences are kept.</p><div class="panel-actions"><button id="cancelRestart" class="secondary">Keep playing</button><button id="confirmRestart" class="primary">Restart from Stage Gate 1</button></div>`);
  $('cancelRestart').onclick=()=>$('details').close();
  $('confirmRestart').onclick=()=>{newPath(progress.seed);lastFocus=$('start');$('details').close();$('start').focus({preventScroll:true});};
  $('cancelRestart').focus({preventScroll:true});
}

function showPanel(kicker,html){
  if(!$('details').open){dialogPrevious=mode;lastFocus=document.activeElement;if(mode==='playing'){mode='dialog';audio.setPlaying(false);input.clear();} $('details').showModal();}
  $('dialogKicker').textContent=kicker;$('dialogBody').innerHTML=html;$('details').scrollTop=0;$('closeDialog').focus({preventScroll:true});
}
$('details').addEventListener('close',()=>{if(mode==='dialog'){mode=dialogPrevious;lastTime=performance.now();accumulator=0;}input.clear();if(mode==='playing'){audio.setPlaying(true);canvas.focus({preventScroll:true});}else if(lastFocus?.isConnected)lastFocus.focus({preventScroll:true});});
$('closeDialog').onclick=()=>$('details').close();
function showDelivery(ev){
 const card=learningCard(ev,run);if(!card)return;
 $('delivery').innerHTML=card.html+'<div class="delivery-actions"><button id="readDelivery" class="text-button">Read full connection ↗</button><button id="closeDelivery" class="text-button" aria-label="Dismiss tool explanation">×</button></div>';$('delivery').hidden=false;deliveryUntil=performance.now()+10000;
 $('readDelivery').onclick=()=>showKnowledge(ev.encounter.id,ev.relation.enablerId);$('closeDelivery').onclick=()=>{$('delivery').hidden=true;canvas.focus({preventScroll:true});};
}
function showKnowledge(id=null,enablerId=null){if(!run)return;const e=run.encounters.find(e=>e.id===id)||currentEncounter(run);if(!e&&!run.world.epilogue&&!run.world.unavailable){notify('Find an incomplete system to reveal its knowledge.');return;}showPanel('BEHIND THIS CHALLENGE',knowledgeHTML(data,run,e,enablerId));$('dialogBody').querySelectorAll('[data-connection]').forEach(b=>b.onclick=()=>showKnowledge(e.id,b.dataset.connection));}
function showMap(){if(!run)return;showPanel('THE JOURNEY · GAME STATE',`<div class="map-gates">${worlds.map((w,i)=>`<span class="map-gate-label ${i===index?'current':''}">${progress.completed.includes(w.gate.id)?'✓':i+1} ${esc(w.alias)}</span>`).join('')}</div>`+`<p><strong>Mini-map ${run.world.roomIndex+1} / ${run.world.roomCount}</strong> · ${run.world.chapterIds.length} blockers across this Stage Gate. Use T or Portals to see entrances and dependencies.</p>`+mapHTML(run,data));$('dialogBody').querySelectorAll('[data-map-node]').forEach(b=>b.onclick=()=>showKnowledge(b.dataset.mapNode));}
function applyAbility(family){if(!run||mode!=='playing')return;handle([useAbility(run,family)]);hud();if(mode==='playing')canvas.focus({preventScroll:true});}
function showPortals(){
 if(!run)return;if(!canTravel(run)){notify('Find the central portal, or acquire a highly connected capability to travel from anywhere.',5);return;}
 persist();const chapter=worlds[index],fast=hasFastTravel(run);
 showPanel('CONNECTED MINI-MAPS',`<h2>Choose a passage.</h2><p>Each mini-map contains part of this Stage Gate. Entrances marked as dependencies use real source links. Other entrances are exploration gates in the game. Cyclic dependencies never lock their own tools.</p>${chapter.rooms.map((room,i)=>{const unlocked=roomUnlocked(room,progress),opened=room.encounters.filter(e=>progress.applied.some(a=>a.blockerId===e.id)).length;return `<button class="alternative" data-room="${i}" ${unlocked?'':'disabled'}><strong>${i===run.world.roomIndex?'You are here · ':''}Mini-map ${i+1} · ${opened} / ${room.encounters.length} paths opened</strong><span>${room.encounters.map(e=>esc(e.blocker.title)).join(' · ')||'Handover signals'}</span>${!unlocked?`<span>${room.sourceGate?'Dependency passage — open:':'Exploration passage — open one path in the preceding mini-map:'} ${room.entryRequirements.map(id=>esc(data.blockerMap.get(id).title)).join(' / ')}</span>`:''}</button>`;}).join('')}${fast?'<h3>Direct discovery portals</h3>'+chapter.rooms.filter(room=>roomUnlocked(room,progress)).map(room=>room.encounters.map(e=>`<button class="alternative" data-room="${room.roomIndex}" data-target="${esc(e.id)}"><strong>${esc(e.blocker.title)}</strong><span>Direct arrival · Mini-map ${room.roomIndex+1}</span></button>`).join('')).join(''):''}<p class="small">Highly connected enablers (linked to at least four blockers) or opened blockers supporting at least three others allow fast travel from anywhere. Other travel starts at the central portal.</p>`);
 $('dialogBody').querySelectorAll('[data-room]').forEach(b=>b.onclick=()=>{const room=Number(b.dataset.room);if(!roomUnlocked(chapter.rooms[room],progress))return;prepare(index,room);if(b.dataset.target){arriveAt(run,b.dataset.target);renderer.reset(run);}lastFocus=$('start');$('details').close();});
}
function showInventory(family=null){
  if(!run)return;const e=currentEncounter(run),records=[];
  for(const id of run.inventory){const links=e?e.relations.filter(r=>r.enablerId===id):[],source=links.length?links:data.relationships.filter(r=>r.enablerId===id);const families=[...new Set(source.map(r=>r.mechanism))];if(family&&!families.includes(family))continue;records.push({enabler:data.enablerMap.get(id),families,relevant:links.length>0});}
  records.sort((a,b)=>Number(b.relevant)-Number(a.relevant));
  showPanel('YOUR CAPABILITY CONSTELLATION',`<h2>${family?esc(family):'What you can bring to the system.'}</h2>${family?`<p class="source-text">${esc(data.mechanismMap.get(family)?.description)}</p>`:'<p>Select an individual enabling capability. A shared mechanism does not make different enablers interchangeable.</p>'}${records.length?records.map(r=>`<button class="alternative ${run.selected===r.enabler.id?'selected':''}" data-select-capability="${esc(r.enabler.id)}"><strong>${esc(r.enabler.title)}</strong><span>${esc(r.families.join(' · '))}${e?r.relevant?' · Linked to this challenge':' · Not linked to this challenge':''}${run.selected===r.enabler.id?' · Selected':''}</span></button>`).join(''):'<p>No capabilities in this family discovered yet. Explore the gold-lit branches near an encountered system.</p>'}`);
  $('dialogBody').querySelectorAll('[data-select-capability]').forEach(b=>b.onclick=()=>{run.selected=b.dataset.selectCapability;hud();$('details').close();notify('Capability selected.');});
}
function cycle(){if(!run)return;const selected=cycleCapability(run);if(selected){notify(data.enablerMap.get(selected).title,3);hud();}}
function help(){showPanel('HOW THE JOURNEY WORKS',`<h2>Explore. Return. Change the system.</h2><p>You are a small light moving through a connected landscape. The central portal is your point of return.</p><ol><li><strong>Move and jump along the stepping stones.</strong> Hold a direction and jump to climb. Follow a branch until you find an incomplete system.</li><li><strong>Look elsewhere for a capability.</strong> Encountering a system illuminates linked enablers on nearby upper and lower routes. Each gold light is an individual capability from the Explorer.</li><li><strong>Return and choose your approach.</strong> Use the capability selector or Q; then E, or a discovered mechanism key (1–6). At the round node, press E or Use. Collect every linked tool shown by the counter before opening the system. This is a game collection rule, not a claim that every source enabler is mandatory in reality.</li><li><strong>Follow the change.</strong> Cross the new route. The round node and the far anchor now provide an E shortcut back to the central portal. Connected challenges may gain a supporting route.</li><li><strong>Continue when the selected paths are open.</strong> Return to the central portal and press E. It offers the next mini-map until every blocker in the Stage Gate is opened.</li></ol><p><strong>Keyboard:</strong> arrows / A / D move; Space / W / Up jump; Down / S drop through a platform; E use; Q cycle; 1–6 use ability; T portals; K knowledge; M map; P / Escape pause. On touchscreens, hold movement and tap or hold Jump. Use ◇ to choose a capability.</p><p>Use Restart to begin again at Stage Gate 1; a confirmation protects your progress from accidental clicks. Falls return you to a recent safe checkpoint. Acquired capabilities stay with you. Different enablers may offer legitimate alternative approaches. Dependency knots and echoes influence routes, but never create impossible prerequisite cycles.</p><h3>Abilities you can use</h3><ul>${Object.entries(ABILITIES).map(([family,a])=>`<li><strong>${a.key} · ${family} — ${a.name}:</strong> ${a.hint}</li>`).join('')}</ul><p>At a blocker with every tool collected, a linked ability also opens its barrier. Elsewhere, abilities change movement or reveal steps. Locked abilities become available as you collect real enablers. The six family buttons work on touchscreens.</p><label class="settings"><input id="motionSetting" type="checkbox" ${progress?.settings.reducedMotion?'checked':''}> Reduce atmospheric motion and camera effects</label><p class="small">The system's reduced-motion preference is always respected. Use ♫ Music in the game header to enable the ambient soundtrack and effects. Music pauses while you read or pause the game. Progress is stored on this device. Game state does not alter Explorer bookmarks or maturity answers.</p>`);$('motionSetting').onchange=event=>{if(progress){progress.settings.reducedMotion=event.target.checked;applySettings();persist();}};}

function finish(){mode='complete';audio.setPlaying(false);input.clear();if(!progress.completed.includes(run.world.gate.id))progress.completed.push(run.world.gate.id);persist();gates();hud();$('pause').disabled=true;audio.play('complete');const final=index===worlds.length-1;overlay({title:final?'The system keeps moving.':'Path established.',text:final?'Scaling is not the end of the journey. It is the ability to keep learning, operating and adapting as conditions change.':run.world.gate.label,button:final?'Run another path →':`Continue to Stage Gate ${worlds[index+1].gate.id} →`,kicker:final?'LIGHT · CONNECTION · CONTINUITY':`STAGE GATE ${run.world.gate.id}`,note:'Game progress is not an assessment of organisational maturity or readiness.',extra:final?finaleHTML(run):recapHTML({...run,encounters:worlds[index].rooms.flatMap(room=>createRun(room,progress).encounters),world:{...run.world,dependencyLinks:worlds[index].rooms.flatMap(room=>room.dependencyLinks)}},data),map:true});$('start').focus({preventScroll:true});}
function handle(events){let changed=false;for(const ev of events){renderer.react(ev);if(['encounter','collect'].includes(ev.type))noticeQueue.push(discoveryNotice(ev));if(ev.type==='open')showDelivery(ev);
  if(ev.type==='ability')notify(`${ABILITIES[ev.family]?.name||ev.family} · ${ABILITIES[ev.family]?.hint||''}`);if(ev.type==='ability-locked')notify('Discover an enabler in this mechanism family to unlock its ability.');if(ev.type==='ability-cooldown')notify('This ability is recharging.');if(ev.type==='tools-missing')notify(`${ev.missing.length} tools still missing for this blocker.\n${ev.missing.map(a=>a.enabler.title).join(' · ')}`,6);if(ev.type==='portals'){persist();showPortals();}if(ev.type==='encounter'){changed=true;}
  if(ev.type==='collect'){audio.play('collect');changed=true;}
  if(ev.type==='open'){audio.play('open');changed=true;}
  if(ev.type==='crossed'){notify('A return shortcut is ready. Use E at the anchor.');changed=true;}
  if(ev.type==='return'){notify('Connection followed. Back at the central portal.');audio.play('return');}
  if(ev.type==='unavailable')notify(ev.hasAlternative?'Choose a linked capability with Q or the capability selector.':'Another capability is needed. Explore the nearby gold-lit branches.');
  if(ev.type==='distant')notify('Use a capability at an incomplete system’s round node.');
  if(ev.type==='home')notify(run.encounters.length?`${ev.remaining} selected paths remain. Explore the branches above and to either side.`:'Visit each handover signal, then return here.');
  if(ev.type==='signal'){notify(ev.signal.label+'.');audio.play('signal');changed=true;}
  if(ev.type==='respawn')notify('A soft landing. Your discovered capabilities are still with you.');
  if(ev.type==='complete'){finish();return;}
 }if(changed){hud();persist();}}

$('portals').onclick=showPortals;$('restart').onclick=requestRestart;$('start').onclick=play;$('pause').onclick=togglePause;$('help').onclick=help;$('mapButton').onclick=showMap;$('orientation').onclick=showMap;$('overlayMap').onclick=showMap;$('knowledge').onclick=()=>showKnowledge();$('inventoryButton').onclick=()=>showInventory();$('touchCycle').onclick=()=>showInventory();
$('sound').onclick=()=>{if(!progress)return;progress.settings.sound=!progress.settings.sound;audio.unlock(progress.settings.sound);audio.play('collect');applySettings();persist();if(mode==='playing')canvas.focus({preventScroll:true});};
window.addEventListener('pagehide',persist);
function frame(now){const dt=Math.min(.05,(now-(lastTime||now))/1000);lastTime=now;if(mode==='playing'){accumulator+=dt;while(accumulator>=1/120&&mode==='playing'){handle(step(run,input.sample(),1/120));accumulator-=1/120;}}else accumulator=0;if(!document.hidden&&(mode==='playing'||now-lastRender>100)){renderer?.render(run,Math.min(.1,(now-lastRender)/1000),now/1000,mode);lastRender=now;}if(run&&run.focusId!==lastHUDFocus&&mode==='playing'){hud();lastHUDFocus=run.focusId;}if($('toast').textContent&&now>toastUntil)$('toast').textContent='';if(!$('toast').textContent&&noticeQueue.length&&mode==='playing')notify(noticeQueue.shift(),6);if(!$('delivery').hidden&&now>deliveryUntil)$('delivery').hidden=true;requestAnimationFrame(frame);}
async function load(){mode='loading';$('start').disabled=true;$('start').textContent='Loading the knowledge network…';$('overlayExtra').innerHTML='';try{if(!renderer)throw new Error('Canvas is unavailable');const response=await fetch('../data/explorer-data.json',{cache:'no-cache',signal:AbortSignal.timeout(15000)});if(!response.ok)throw new Error(`Explorer data: HTTP ${response.status}`);data=prepareData(await response.json());if(data.warnings.length)console.warn('Scale Run data validation:',data.warnings);try{storage=window.localStorage;}catch{storage={getItem:()=>null,setItem:()=>{throw new Error('Unavailable storage');}};}progress=readProgress(storage,data);worlds=buildCampaign(data,progress.seed);progress=reconcileCampaign(progress,worlds);applySettings();let next=worlds.findIndex(w=>w.gate.id===progress.settings.currentGate);if(next<0)next=worlds.findIndex(w=>!progress.completed.includes(w.gate.id));if(next<0)next=0;if(next>0&&!progress.completed.includes(worlds[next-1].gate.id))next=0;const room=Math.min(progress.settings.currentRoom||0,worlds[next].rooms.length-1);prepare(next,roomUnlocked(worlds[next].rooms[room],progress)?room:0);}catch(error){console.error('Scale Run startup failed:',error);mode='error';overlay({title:'The knowledge network could not be loaded.',text:'Scale Run uses the live Explorer data. Please try again, or return to the Explorer.',button:'Try again',extra:'<a class="recap-link" href="../#explore">Return to Explorer ↗</a>',note:'Your saved progress has not been removed.'});}}
requestAnimationFrame(frame);load();
