import {esc} from './ui.mjs';
export function excerpt(text,limit=240){const s=String(text||'').trim();if(s.length<=limit)return s;const end=s.lastIndexOf(' ',limit);return s.slice(0,end>0?end:limit)+'…';}
export function learningCard(event,run){
 const e=event.encounter;
 if(event.type==='encounter')return {kicker:'1 · BLOCKER DISCOVERED',html:`<h2>${esc(e.blocker.title)}</h2><p class="discovery-copy">${esc(excerpt(e.blocker.statement))}</p><p class="next-step"><strong>Your next move:</strong> explore the gold lights around this system. They contain enabling capabilities. Collect a linked capability, then return to this round node and press E / Use.</p>`};
 if(event.type==='collect')return {kicker:'2 · ENABLER DISCOVERED',html:`<h2>${esc(event.pickup.enabler.title)}</h2><p class="discovery-copy">${esc(excerpt(event.pickup.enabler.description))}</p><p><strong>${esc(event.pickup.relation.mechanism)}</strong> · ${esc(excerpt(event.pickup.relation.rationale,200))}</p><p class="next-step"><strong>Your next move:</strong> return to <strong>${esc(e.blocker.title)}</strong>. This capability is selected. Press E / Use at its round node to apply it.</p>`};
 if(event.type==='open'){const acquired=e.relations.filter(r=>run.inventory.has(r.enablerId));return {kicker:'3 · TOOLS BECOME A PATH',html:`<h2>${esc(e.blocker.title)}</h2><div class="tool-assembly" aria-hidden="true">◇ <span>→</span> ◎ <span>→</span> ↗</div><p>The selected enabling action has opened this path. Here is how the capabilities you discovered relate to this blocker:</p>${acquired.map(r=>`<article class="tool-explanation"><strong>${esc(run.world.pickups.find(p=>p.enabler.id===r.enablerId)?.enabler.title||r.mechanism)}</strong><p>${esc(r.rationale)}</p></article>`).join('')}<p class="next-step"><strong>Your next move:</strong> cross the new passage. Press E at its far anchor to return to the central portal. Open every remaining challenge, then use the central portal to finish the chapter.</p><p class="small">This is a game transformation. Real blockers may require several coordinated enabling actions.</p>`};}
 return null;
}
export function journeyStep(run){if(run.world.epilogue||run.world.unavailable)return run.signals.size===run.world.signals.length?3:1;if(run.encounters.every(e=>e.opened))return 3;const e=run.encounters.find(e=>e.id===run.focusId);if(!e||e.opened)return 0;return e.relations.some(r=>run.inventory.has(r.enablerId))?2:1;}
