import {connectionURL} from './data.mjs';
import {platforms} from './engine.mjs';
import {powerStyle} from './config.mjs';
export const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export const gateURL=gate=>`../#stage-gates/${encodeURIComponent(gate.id)}`;
const paragraph=(label,text)=>text?`<h3>${label}</h3><p class="source-text">${esc(text)}</p>`:'';

export function knowledgeHTML(data,run,encounter,enablerId=null) {
  if(!encounter)return `<h2>Carry learning forward.</h2><p>${run.world.epilogue?'This Stage Gate currently contains no mapped blocker challenges.':'No usable blocker–enabler connections are available for this gate.'}</p><p>The handover signals are narrative game metaphors for knowledge preservation, responsibility transfer and continuity. They are not blockers or enablers added to the source.</p><a href="${gateURL(run.world.gate)}" target="_blank" rel="noopener">Explore this Stage Gate ↗</a>`;
  const b=encounter.blocker,relation=encounter.relations.find(r=>r.enablerId===(enablerId||encounter.chosen||run.selected))||encounter.alternatives[0].relation,enabler=data.enablerMap.get(relation.enablerId),domain=data.domains.find(d=>d.slug===b.domain);
  const deps=(ids,direction)=>ids.length?`<h3>${direction}</h3><ul class="dependency-list">${ids.map(id=>{const other=data.blockerMap.get(id),local=run.encounters.find(e=>e.id===id);return `<li><a href="${connectionURL(other)}" target="_blank" rel="noopener">${esc(other.title)}</a><br><span>${local?(local.opened?'Path opened in this run':local.encountered?'Encountered in this run':'Not yet encountered'):run.priorOpened.has(id)?'Supporting path opened in an earlier chapter':other.stageGate===b.stageGate?'Outside this selected path':'Echo from Stage Gate '+esc(other.stageGate)} · ${esc(data.gateMap.get(other.stageGate)?.label)}</span></li>`;}).join('')}</ul>`:'';
  return `<p class="eyebrow">THE BLOCKER · ${encounter.opened?'PATH OPENED IN GAME':'ENCOUNTERED IN GAME'}</p><h2>${esc(b.title)}</h2><p class="source-text">${esc(b.statement)}</p><div class="metadata"><span>${esc(domain?.title||b.domain)}</span><span>${esc(b.dimension)}</span><span>${esc(run.world.gate.label)}</span></div>${paragraph('Why it matters',b.whyItMatters)}${paragraph('Consequence',b.consequence)}${paragraph('Stakeholders',b.stakeholders.join(' · '))}<section class="source-section"><p class="eyebrow">THE ENABLER</p><div class="connection-card" style="--power:${powerStyle(relation.mechanism).color}"><h3>${esc(enabler.title)}</h3><p class="source-text">${esc(enabler.description)}</p>${paragraph('Practical actions',enabler.practicalActions)}${paragraph('Expected outcome',enabler.expectedOutcome)}${paragraph('Stakeholders',enabler.stakeholders.join(' · '))}<p class="eyebrow">THE CONNECTION · ${esc(relation.mechanism)}</p><p class="source-text">${esc(data.mechanismMap.get(relation.mechanism)?.description)}</p><p class="source-text">${esc(relation.rationale)}</p></div><a href="${connectionURL(b,enabler.id)}" target="_blank" rel="noopener">Open this connection in the Explorer ↗</a><p class="small">This enabling action changes the path in Scale Run. In practice, blockers may require several coordinated actions.</p></section><section class="source-section"><p class="eyebrow">ALTERNATIVE ENABLING APPROACHES</p>${encounter.relations.filter(r=>r!==relation).map(r=>`<button class="alternative" data-connection="${esc(r.enablerId)}"><strong>${esc(data.enablerMap.get(r.enablerId).title)}</strong><span>${esc(r.mechanism)} · ${run.inventory.has(r.enablerId)?'Capability discovered':'Source alternative'}</span></button>`).join('')||'<p>This source lists one enabling approach.</p>'}</section><section class="source-section"><p class="eyebrow">CONNECTED CHALLENGES</p>${encounter.knot?'<p class="small">This challenge belongs to a dependency knot. These connected systems influence one another; the game never makes a cycle into a progression lock.</p>':''}${deps(encounter.upstream,'This blocker depends on')}${deps(encounter.downstream,'Other blockers that depend on this one')}${!encounter.upstream.length&&!encounter.downstream.length?'<p>No dependencies are currently mapped.</p>':''}</section><div class="panel-actions"><a href="${gateURL(run.world.gate)}" target="_blank" rel="noopener">Explore this Stage Gate ↗</a><a href="../#domain/${encodeURIComponent(b.domain)}" target="_blank" rel="noopener">Explore this domain ↗</a></div>`;
}

export function mapHTML(run,data){
  const nodeMap=new Map(run.encounters.map(e=>[e.id,e]));
  const lines=run.world.dependencyLinks.filter(l=>!l.echo).map(l=>{const a=nodeMap.get(l.from),b=nodeMap.get(l.to);if(!a.encountered||!b.encountered)return '';return `<path d="M${a.x},${a.y-35} Q${(a.x+b.x)/2},${Math.min(a.y,b.y)-170} ${b.x},${b.y-35}" fill="none" stroke="${a.opened?'#428c7d':'#87a9b0'}" stroke-width="7" ${a.opened?'':'stroke-dasharray="12 16"'} marker-end="url(#arrow)"/>`;}).join('');
  const echoes=run.world.dependencyLinks.filter(l=>l.echo&&nodeMap.get(l.to)?.encountered).slice(0,12).map((l,i)=>{const e=nodeMap.get(l.to),x=e.x+(i%2?-145:145),y=e.y-120-(i%3)*38;return `<path d="M${x},${y} L${e.x},${e.y-35}" stroke="#8ba6b0" stroke-width="3" stroke-dasharray="9 14"/><circle cx="${x}" cy="${y}" r="12" fill="#eef5ec" stroke="#8ba6b0" stroke-width="4"/>`;}).join('');
  const pickups=run.world.pickups.filter(p=>run.inventory.has(p.enabler.id)).map(p=>`<circle cx="${p.x}" cy="${p.y-28}" r="15" fill="#dcc183" stroke="#a28b52" stroke-width="4"/>`).join('');
  const nodes=run.encounters.map((e,i)=>`<g><circle cx="${e.x}" cy="${e.y-35}" r="${e.knot?44:35}" fill="${e.opened?'#8bbc9f':e.encountered?'#eff4e5':'#ccdcda'}" stroke="${e.opened?'#4b8f76':'#698e9b'}" stroke-width="6"/><text x="${e.x}" y="${e.y-24}" text-anchor="middle" font-size="33" fill="#315d67">${e.opened?'✓':e.encountered?i+1:'·'}</text></g>`).join('');
  return `<h2>A connected place.</h2><p class="small">${esc(run.world.gate.label)} · ${run.world.encounters.length} selected challenges out of ${run.world.mappedCount} mapped blockers.</p><svg class="world-map" viewBox="0 0 ${run.world.width} ${run.world.height}" role="img" aria-label="Map of the current game world. Your spark is white, discovered capabilities are gold, opened paths have ticks, and arrows point from supporting challenges towards dependent challenges."><defs><marker id="arrow" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="5" markerHeight="5" orient="auto-start-reverse"><path d="M0 0 L10 5 L0 10" fill="#668e91"/></marker></defs>${platforms(run).map(p=>`<rect x="${p.x}" y="${p.y}" width="${p.w}" height="12" rx="6" fill="#759e9980"/>`).join('')}${lines}${echoes}${pickups}${nodes}${run.world.signals.map(s=>`<circle cx="${s.x}" cy="${s.y}" r="27" fill="${run.signals.has(s.key)?'#86b99f':'#e6d29b'}"/>`).join('')}<ellipse cx="${run.world.exit.x}" cy="${run.world.exit.y-35}" rx="26" ry="40" fill="none" stroke="#5a9290" stroke-width="6"/><circle cx="${run.player.x+12}" cy="${run.player.y+14}" r="24" fill="#fffdf0" stroke="#365e6f" stroke-width="7"/></svg><div class="map-key"><span>○ Unexplored</span><span>◎ Encountered</span><span>✓ Path opened</span><span>◇ Capability discovered</span><span>⇢ Dependency echo</span></div><div class="map-nodes">${run.encounters.map((e,i)=>`<button class="map-node ${e.opened?'opened':''}" data-map-node="${esc(e.id)}" ${e.encountered?'':'disabled'}><span>${e.opened?'PATH OPENED':e.encountered?'ENCOUNTERED':'UNEXPLORED'}${e.knot?' · DEPENDENCY KNOT':''}</span>${e.encountered?esc(e.blocker.title):'Unexplored system '+(i+1)}</button>`).join('')}</div>${run.world.epilogue?'<p>No mapped blocker challenges in this gate. The handover signals are narrative metaphors.</p>':''}<p class="small">Dependencies influence connections and supporting routes. An opened path does not automatically open another challenge. Echoes refer to real source blockers outside this selected path.</p><a href="${gateURL(run.world.gate)}" target="_blank" rel="noopener">Explore all knowledge in this Stage Gate ↗</a>`;
}

export function recapHTML(run,data){
  const opened=run.encounters.filter(e=>e.opened),stakeholders=new Set(opened.flatMap(e=>[...e.blocker.stakeholders,...data.enablerMap.get(e.chosen).stakeholders])),mechanisms=new Set(opened.map(e=>e.mechanism));
  if(!opened.length)return '';
  return `<div class="recap-stats"><span><b>${opened.length}</b>selected paths opened</span><span><b>${mechanisms.size}</b>mechanisms used</span><span><b>${stakeholders.size}</b>stakeholder groups</span></div><div class="recap-connections">${opened.map(e=>`<div class="recap-row"><b>${esc(e.blocker.title)}</b><em>←</em><span>${esc(data.enablerMap.get(e.chosen).title)}</span></div>`).join('')}</div><p class="small">${run.world.dependencyLinks.length} source dependency connections in this selected journey.</p><a class="recap-link" href="${gateURL(run.world.gate)}" target="_blank" rel="noopener">Explore all ${run.world.mappedCount} blockers in this Stage Gate ↗</a>`;
}

export function finaleHTML(run){
  const keys=[...run.mechanisms],nodes=keys.map((key,i)=>({key,x:300+Math.cos(i*Math.PI*2/Math.max(1,keys.length))*125,y:75+Math.sin(i*Math.PI*2/Math.max(1,keys.length))*45}));
  return `<svg class="final-network" viewBox="0 0 600 150" role="img" aria-label="Your discovered mechanism families form a connected, continuing system"><ellipse cx="300" cy="75" rx="145" ry="54" fill="none" stroke="#6d9d9c" opacity=".4"/>${nodes.map(n=>`<path d="M300 75 Q${n.x} 75 ${n.x} ${n.y}" fill="none" stroke="#8fb7ad"/><circle cx="${n.x}" cy="${n.y}" r="6" fill="${powerStyle(n.key).color}"/><text x="${n.x}" y="${n.y+21}" text-anchor="middle" font-size="10" fill="#426971">${esc(n.key)}</text>`).join('')}<circle cx="300" cy="75" r="13" fill="#fffcee" stroke="#80aaa1"/><path d="M284 100 Q321 92 315 47 L310 56 M315 47 L324 54" fill="none" stroke="#4e8a97" stroke-width="2"/></svg><a class="recap-link" href="../#explore">Explore the knowledge →</a>`;
}
