import {esc,mapHTML} from './ui.mjs?v=8';
import {createRun,portalOpen} from './engine.mjs?v=8';
export function worldMapModel(chapter,run,progress){
 const visited=new Set([...(progress.zones||[]),run.world.discoveryKey]),visible=new Set(),open=new Set([run.world.roomIndex]);
 for(const room of chapter.rooms)if(visited.has(room.discoveryKey)){visible.add(room.roomIndex);const state=createRun(room,progress);for(const p of room.portals){visible.add(p.targetRoom);if(portalOpen(state,p))open.add(p.targetRoom);}}
 const frame=run.timers.Frame>run.time;if(frame)chapter.rooms.forEach(r=>visible.add(r.roomIndex));
 return {zones:chapter.rooms.map(r=>({id:r.roomIndex,visited:visited.has(r.discoveryKey),visible:visible.has(r.roomIndex),accessible:open.has(r.roomIndex),current:r.roomIndex===run.world.roomIndex,name:visited.has(r.discoveryKey)?r.zoneName:'Unexplored region',position:r.mapPosition})),edges:chapter.rooms.flatMap(r=>visited.has(r.discoveryKey)?r.portals.map(p=>({from:r.roomIndex,to:p.targetRoom,open:portalOpen(createRun(r,progress),p),shortcut:!!p.shortcut})):[])};
}
export function worldMapHTML(chapter,run,progress,data,selected=run.world.roomIndex,overview=false){
 if(!overview){const room=chapter.rooms[selected],visited=selected===run.world.roomIndex||(progress.zones||[]).includes(room?.discoveryKey);if(!visited)selected=run.world.roomIndex;const shown=chapter.rooms[selected],view=selected===run.world.roomIndex?run:{...createRun(shown,progress),mapPreview:true};return `<div class="map-navigation"><button data-map-zoom="out">− Zoom out · World</button>${selected!==run.world.roomIndex?'<button data-map-current>◎ Current region</button>':''}</div><h2>${esc(shown.zoneName)}${selected===run.world.roomIndex?' · You are here':''}</h2>`+mapHTML(view,data,false);}
 const model=worldMapModel(chapter,run,progress),visible=model.zones.filter(z=>z.visible),seenEdges=new Set();
 const paths=model.edges.map(e=>{const key=[Math.min(e.from,e.to),Math.max(e.from,e.to),e.shortcut].join(':');if(seenEdges.has(key))return '';seenEdges.add(key);const [x,y]=model.zones[e.from].position,[xx,yy]=model.zones[e.to].position;return `<path d="M${x} ${y} Q${(x+xx)/2} ${(y+yy)/2-(e.shortcut?40:0)} ${xx} ${yy}" stroke="${e.open?'#4f9585':'#82959e'}" stroke-width="${e.shortcut?2:4}" stroke-dasharray="${e.shortcut?'3 8':e.open?'none':'9 10'}" fill="none"/>`;}).join('');
 const nodes=visible.map(z=>{const [x,y]=z.position,r=chapter.rooms[z.id];return `<g><rect x="${x-75}" y="${y-45}" width="150" height="90" rx="${r.design.shape==='modules'?8:30}" fill="${z.current?'#e1f2da':z.visited?'#eff5ea':'#e0e7e580'}" stroke="${z.current?'#347b76':'#9cb7b3'}" stroke-width="${z.current?4:2}" ${z.visited?'':'stroke-dasharray="5 7"'}/>${z.visited?r.platforms.filter((_,i)=>i%4===0).map(p=>`<path d="M${x-58+p.x/r.width*116} ${y-31+p.y/r.height*50} h${Math.max(3,p.w/r.width*116)}" stroke="#779f9490" stroke-width="2"/>`).join(''):''}<text x="${x}" y="${y+12}" text-anchor="middle" font-size="13" fill="#345d66">${esc(z.name)}</text><text x="${x}" y="${y+31}" text-anchor="middle" font-size="10" fill="#496e73">${z.current?'YOU ARE HERE':z.visited?'Visited':z.accessible?'Passage available':'Passage sealed'}</text></g>`;}).join('');
 return `<div class="map-navigation"><button data-map-zoom="in">+ Zoom in · Current region</button></div><h2>Stage Gate ${esc(chapter.gate.id)} — ${esc(chapter.gate.label)}</h2><p>You are in <strong>${esc(run.world.zoneName)}</strong>. Inspect a discovered region to remember its encounters. Travel through the landscape.</p><div class="atlas-pan" role="region" aria-label="Scrollable world overview" tabindex="0"><svg class="world-overview" viewBox="0 0 760 455" role="img" aria-label="World overview. Current region: ${esc(run.world.zoneName)}. Solid connections are open, dashed connections sealed, dotted connections shortcuts.">${paths}${nodes}</svg></div><p class="atlas-touch-hint">Swipe the overview sideways to inspect its connections.</p><div class="map-key"><span>━━ Open passage</span><span>┄ Sealed passage</span><span>··· Shortcut</span></div><div class="zone-tabs">${visible.map(z=>`<button data-zone="${z.id}" ${z.visited?'':'disabled'} class="${z.id===selected?'selected':''}">${esc(z.name)}${z.current?' · You are here':''}</button>`).join('')}</div>`;
}
